### ISSUE TITLE
Can you launch a more detailed source code?

### ISSUE THREAD

**Issue by mk-runner** [Wangyixinxin/MRG-KG#1]
A very valuable work.  If the source code can be made public (such as the entire model, how to calculate DOR and DS, and how to use disease-organs pairs), the influence may be even greater.

Look forward to your detailed source code. Thank you!

**Comment by Wangyixinxin** [comment]
Hi, we have published all the codes relevant to our paper, please refer to README.md. 
Since our contribution is on the dataset, not the generation model, we directly used the R2Gen model (link can be found in README and our paper). You can use our code to generate an augmented dataset, train the R2Gen model and evaluate the results using our new score.  

Btw, the disease-organ pairs are utilized in our codes to augment the dataset and calculate DS/DOR scores.

Best.
